---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: true

platforms:
- name: ubuntu-12.10
  network:
    - ["forwarded_port", {guest: 80, host: 8080, guest: 443, host: 8443}]
  run_list:
    - recipe[apt]
- name: ubuntu-12.04
  network:
    - ["forwarded_port", {guest: 80, host: 8080, guest: 443, host: 8444}]
  run_list:
    - recipe[apt]
- name: ubuntu-14.04
  network:
    - ["forwarded_port", {guest: 80, host: 8080, guest: 443, host: 8444}]
  run_list:
    - recipe[apt]
- name: debian-7
  driver_config:
    box: opscode-debian-7.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box
  run_list:
  - recipe[apt]

suites:

- name: ldap
  run_list:
    - recipe[openldap::server]
    - recipe[openldap::users]
    - recipe[zarafa::ldap-additions]
    - recipe[zarafa]
    - recipe[phpldapadmin]
#    - recipe[minitest-handler]
  attributes:
    zarafa:
      backend_type: ldap
      mysql_password: test
    openldap:
      rootpw: secretsauce
      roothash: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/"
      preseed_dir: "/tmp/does_not_exist"
    mysql:
      server_debian_password: test
      server_backup_password: test
      server_root_password: test
      server_repl_password: test

- name: mysql
  run_list:
    - recipe[zarafa]
    - recipe[zarafa::z-push]
#    - recipe[minitest-handler]
  attributes:
    zarafa:
      backend_type: mysql
      mysql_password: test
      catchall_user: me@example.com
      timezone: Europe/Berlin
    mysql:
      server_debian_password: test
      server_backup_password: test
      server_root_password: test
      server_repl_password: test

- name: zarafa-import-export
  run_list:
    - recipe[zarafa]
    - recipe[zarafa::zarafa-export]
    - recipe[zarafa::zarafa-import]
#    - recipe[minitest-handler]
  attributes:
    zarafa:
      backend_type: mysql
      mysql_password: test
      catchall_user: me@example.com
      timezone: Europe/Berlin
    mysql:
      server_debian_password: test
      server_backup_password: test
      server_root_password: test
      server_repl_password: test

